spring:
  application:
    name: todoApp

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secretKey: asgasdg4631agadf4g6d4fah31ad3fh6df4h631